<h1>Error</h1>
<p>Class <code>Napi::Error</code> inherits from class <a href="./object_reference.md"><code>Napi::ObjectReference</code></a> and class <a href="https://cplusplus.com/reference/exception/exception/"><code>std::exception</code></a>.</p>
<p>The <code>Napi::Error</code> class is a representation of the JavaScript <code>Error</code> object that is thrown
when runtime errors occur. The Error object can also be used as a base object for
user-defined exceptions.</p>
<p>The <code>Napi::Error</code> class is a persistent reference to a JavaScript error object thus
inherits its behavior from the <code>Napi::ObjectReference</code> class (for more info see: <a href="object_reference.md"><code>Napi::ObjectReference</code></a>).</p>
<p>If C++ exceptions are enabled (for more info see: <a href="setup.md">Setup</a>), then the
<code>Napi::Error</code> class extends <code>std::exception</code> and enables integrated
error-handling for C++ exceptions and JavaScript exceptions.</p>
<p>For more details about error handling refer to the section titled <a href="error_handling.md">Error handling</a>.</p>
<h2>Methods</h2>
<h3>New</h3>
<p>Creates empty instance of an <code>Napi::Error</code> object for the specified environment.</p>
<pre><code class="language-cpp">Napi::Error::New(Napi::Env env);
</code></pre>
<ul>
<li><code>[in] env</code>: The environment in which to construct the <code>Napi::Error</code> object.</li>
</ul>
<p>Returns an instance of <code>Napi::Error</code> object.</p>
<h3>New</h3>
<p>Creates instance of an <code>Napi::Error</code> object.</p>
<pre><code class="language-cpp">Napi::Error::New(Napi::Env env, const char* message);
</code></pre>
<ul>
<li><code>[in] env</code>: The environment in which to construct the <code>Napi::Error</code> object.</li>
<li><code>[in] message</code>: Null-terminated string to be used as the message for the <code>Napi::Error</code>.</li>
</ul>
<p>Returns instance of an <code>Napi::Error</code> object.</p>
<h3>New</h3>
<p>Creates instance of an <code>Napi::Error</code> object</p>
<pre><code class="language-cpp">Napi::Error::New(Napi::Env env, const std::string&amp; message);
</code></pre>
<ul>
<li><code>[in] env</code>: The environment in which to construct the <code>Napi::Error</code> object.</li>
<li><code>[in] message</code>: Reference string to be used as the message for the <code>Napi::Error</code>.</li>
</ul>
<p>Returns instance of an <code>Napi::Error</code> object.</p>
<h3>Fatal</h3>
<p>In case of an unrecoverable error in a native module, a fatal error can be thrown
to immediately terminate the process.</p>
<pre><code class="language-cpp">static NAPI_NO_RETURN void Napi::Error::Fatal(const char* location, const char* message);
</code></pre>
<p>The function call does not return, the process will be terminated.</p>
<h3>Constructor</h3>
<p>Creates empty instance of an <code>Napi::Error</code>.</p>
<pre><code class="language-cpp">Napi::Error::Error();
</code></pre>
<p>Returns an instance of <code>Napi::Error</code> object.</p>
<h3>Constructor</h3>
<p>Initializes an <code>Napi::Error</code> instance from an existing JavaScript error object.</p>
<pre><code class="language-cpp">Napi::Error::Error(napi_env env, napi_value value);
</code></pre>
<ul>
<li><code>[in] env</code>: The environment in which to construct the error object.</li>
<li><code>[in] value</code>: The <code>Napi::Error</code> reference to wrap.</li>
</ul>
<p>Returns instance of an <code>Napi::Error</code> object.</p>
<h3>Message</h3>
<pre><code class="language-cpp">std::string&amp; Napi::Error::Message() const NAPI_NOEXCEPT;
</code></pre>
<p>Returns the reference to the string that represent the message of the error.</p>
<h3>ThrowAsJavaScriptException</h3>
<p>Throw the error as JavaScript exception.</p>
<pre><code class="language-cpp">void Napi::Error::ThrowAsJavaScriptException() const;
</code></pre>
<p>Throws the error as a JavaScript exception.</p>
<h3>what</h3>
<pre><code class="language-cpp">const char* Napi::Error::what() const NAPI_NOEXCEPT override;
</code></pre>
<p>Returns a pointer to a null-terminated string that is used to identify the
exception. This method can be used only if the exception mechanism is enabled.</p>
